- systemSmartContractsConfig.toml
- changed max number of nodes for staking
> Release 2020.10.03

- api.toml
- config.toml
- gasSchedule.toml
- p2p.toml
- ratings.toml
- systemSmartContractsConfig.toml
> Fixed unbond period

- config.toml
- Split VM config: execution and querying.
> Split VM config: execution and querying

- elasticIndexTemplates/accounts.json
- elasticIndexTemplates/accountshistory.json
- elasticIndexTemplates/accountshistory_policy.json
- elasticIndexTemplates/blocks.json
- elasticIndexTemplates/blocks_policy.json
- elasticIndexTemplates/miniblocks.json
- elasticIndexTemplates/miniblocks_policy.json
- elasticIndexTemplates/opendistro.json
- elasticIndexTemplates/rating.json
- elasticIndexTemplates/rating_policy.json
- elasticIndexTemplates/rounds.json
- elasticIndexTemplates/rounds_policy.json
- elasticIndexTemplates/tps.json
- elasticIndexTemplates/transactions.json
- elasticIndexTemplates/transactions_policy.json
- elasticIndexTemplates/validators.json
- elasticIndexTemplates/validators_policy.json
> Release v1.1.6.1

- config.toml
- genesis.json
- nodesSetup.json
- systemSmartContractsConfig.toml
> Release v1.1.6.2

- genesisSmartContracts.json
- fixed genesisSmartContracts.json (reverted to old addresses)
> Fix genesisSmartContracts.json addresses

- config.toml
- release T1.1.12.0 - enabled relayed transactions and builtin functions
> Release 1.1.12.0 (added forgotten option)

- config.toml
> Make Arwen OOP false

- nodesSetup.json
> Fixed genesis time for T1.1.10.1

- config.toml
- systemSmartContractsConfig.toml
- release T1.1.15.1 - changed the activation epoch to 26
> Release T1.1.15.1

- config.toml
- systemSmartContractsConfig.toml
- release T1.1.23.0 - increased starting epoch
> Release T1.1.23.0

- scripts/run-observer.sh
Added extra checks in the run-observer script.
> Extra checks run-observer script

- scripts/run-observer.sh
Added an extra check if the blockchain is running.
> extra check

- config.toml
- economics.toml
- nodesSetup.json
- systemSmartContractsConfig.toml
- release T1.1.62.1
Genesis time: June 14, 2021 21:00 UTC
> Release T1.1.62.1

- .github/workflows/deploy-docker.yaml
Added a GitHub action that will push on the dockerhub a docker image on every published release.
> Action to push docker image on docker hub

- .github/workflows/deploy-docker.yaml
Instead of using a hardcoded username for Dockerhub login now we use a Github secret
> Use secrets for username

- config.toml
- economics.toml
- nodesSetup.json
- systemSmartContractsConfig.toml
> Release T1.1.64.1

- docker/Dockerfile
removed arwen build step from docker file
> fixed dockerfile

- nodesSetup.json
> Release T1.1.65.2

- nodesSetup.json
> Release T1.1.65.3

- genesis.json
- nodesSetup.json
- release T1.1.65.4
genesis time on 2021.09.06 19:00 UTC
> Release T1.1.65.4

- scripts/run-observer.sh
- fixed script so it will work also with branches
> Fixed script

- nodesSetup.json
> Release T1.2.38.1

- docker/Dockerfile
- Updated the `golang` version from the `Dockerfile`
> Update docker file

- nodesSetup.json
- release T1.2.38.3-rc2
Genesis 2022.03.14 15:00:00 UTC
> Release T1.2.38.3-rc2

- config.toml
- enableEpochs.toml
- nodesSetup.json
> Release T1.3.23.1

- external.toml
- added `collections` in the `external.toml`
> Collections index

- config.toml
> Release T1.3.50.2

- .github/workflows/deploy-docker.yaml
- README.md
- scripts/run-observer.sh
- Changed the image name for Github action
- Updated Readme.md
> Update docker image and readme

- binaryVersion
- config.toml
- enableEpochs.toml
- external.toml
> Release T1.6.2.0

- binaryVersion
> Release T1.6.6.0

- binaryVersion
> Release T1.6.15.0

- docker/Dockerfile
Updated the Dockerfile for conditional copying of required files for amd64/arm64.
> Update the Dockerfile to copy required files for arm build

- .github/workflows/deploy-docker.yaml
- Added docker/metadata-action@v5 to automatically generate image tags and labels
- Replaced manual Docker build and push steps with docker/build-push-action@v5
> Refactor GitHub Actions workflow for building and pushing Docker images.
